.MODEL SMALL
.DATA

	LIST DW 12H,43H,87H,90H		;ARRAY HOLDING 4 ELEMENTS
	COUNT EQU 4			;COUNT WHICH EQUALS THE NUMBER OF ELEMENTS IN THE ARRAY 

.CODE					;START OF THE DATA SEGMENT 

	MOV AX,@DATA			
	MOV DS,AX			
	MOV DX,COUNT-1			;SINCE THE INDEXING OF THE ARRAY WILL START FROM 0
 AGAIN:					;LABEL1

	MOV CX,DX			;CX REGISTER UED FOR LOOPING 
	MOV SI,OFFEST LIST 		;ASSINGING THE OFFSET OD LIST TO SI REGISTER
	
 AGAIN1:				;LABEL2

	MOV AX,[SI]			;MOVING ELEMENT TO AX FOR XCHG IS GREATER
	CMP AX,[SI+2]	
	JL CO				;DOSEN'T COMPARE IF LESSER
	XCHG [SI+2],AX			;EXCHANGE OF --
	XCHG [SI],AX			;--CONSEQUTIVE ELEMENTS
 CO:					;LABEL2

	ADD SI,02			;GOING TO THE NEXT ELEMENT IN THE ARRAY
	LOOP AGAIN1			;LOOPS FOUR TIMES
	DEC DX				
	JNZ AGAIN
	MOV AH,4CH 			;TERMINATION OF PROGRAM
	INT 21H				;DOS INTERRUPT 

	END				;END OF THE PROGRAM
